class Musics {
  int id;
  String name, artis, music, image;
  bool isLiked,isSaved;

  Musics(
      {required this.id, required this.name, required this.music, required this.image, required this.artis,required this.isLiked, required this.isSaved});
}

List<Musics> musicList = [
  Musics(id: 0, name: "Beautiful Things", music: "musics/0beautiful_things.mp3", image: "assets/images/0__.png", artis: "Benson Boone", isLiked: false, isSaved: false),
  Musics(id: 1, name: "Lose Control", music: "musics/1lose_control.mp3", image: "assets/images/1__.png", artis: "Teddy Swims", isLiked: false, isSaved: false),
  Musics(id: 2, name: "Tshwala", music: "musics/2tshwala_bam.mp3", image: "assets/images/2__.png", artis: "Titom & Yuppe", isLiked: false, isSaved: false),
  Musics(id: 3, name: "Mwaki", music: "musics/3mwaki.mp3", image: "assets/images/3__.png", artis: "ZERB & Sofiya Nzau", isLiked: false, isSaved: false),
  Musics(id: 4, name: "One Of The Girls", music: "musics/4one_of_the_girls.mp3", image: "assets/images/4__.jpg", artis: "The Weeknd, JENNIE & Lily Rose Depp", isLiked: false, isSaved: false),
  Musics(id: 5, name: "Redrum", music: "musics/5redrum.mp3", image: "assets/images/5__.jpg", artis: "21 Savage", isLiked: false, isSaved: false),
  Musics(id: 6, name: "Stick Seasons", music: "musics/6stick_season.mp3", image: "assets/images/6__.jpg", artis: "Noah Kahan", isLiked: false, isSaved: false),
  Musics(id: 7, name: "Strangers", music: "musics/7strangers.mp3", image: "assets/images/7__.jpg", artis: "Kenya Grace", isLiked: false, isSaved: false),
  Musics(id: 8, name: "Greedy", music: "musics/8greedy.mp3", image: "assets/images/8__.jpg", artis: "Tate McRae", isLiked: false, isSaved: false),
  Musics(id: 9, name: "Water", music: "musics/9water.mp3", image: "assets/images/9__.jpg", artis: "Tyla", isLiked: false, isSaved: false),
  Musics(id: 10, name: "Made In Romania", music: "musics/10made_in_romania.mp3", image:"assets/images/10__.jpg", artis: "Ionut Cercel", isLiked: false, isSaved: false),
  Musics(id: 11, name: "Another Love", music: "musics/11another_love.mp3", image: "assets/images/11__.png", artis: "Tom Odell", isLiked: false, isSaved: false),
  Musics(id: 12, name: "Wain Meaady", music: "musics/12wain_meaady.mp3", image: "assets/images/12__.png", artis: "El Shab Arab", isLiked: false, isSaved: false),
  Musics(id: 13, name: "Zhurek", music: "musics/13zhurek.mp3", image: "assets/images/13__.png", artis: "Adam", isLiked: false, isSaved: false),
  Musics(id: 14, name: "Somebody That I Used to Know (feat. Kimbra) ", music: "musics/14used_to_know.mp3", image: "assets/images/14__.png", artis: "Gotye", isLiked: false, isSaved: false),
  Musics(id: 15, name: "(It Goes Like) Nanana (Edit) ", music: "musics/15nanana.mp3", image: "assets/images/15__.png", artis: "Peggy Gou", isLiked: false, isSaved: false),
  Musics(id: 16, name: "Bloody Mary", music: "musics/16bloody_mary.mp3", image: "assets/images/16__.png", artis: "Lady Gaga", isLiked: false, isSaved: false),
  Musics(id: 17, name: "La", music: "musics/17la.mp3", image: "assets/images/17__.png", artis: "Distinct", isLiked: false, isSaved: false),
  Musics(id: 18, name: "Daylight", music: "musics/18daylight.mp3", image: "assets/images/18__.png", artis: "David Kushner", isLiked: false, isSaved: false),
  Musics(id: 19, name: "The Way I are", music: "musics/19the_way_are.mp3", image: "assets/images/19__.png", artis: "Timbaland", isLiked: false, isSaved: false),
  Musics(id: 20, name: "The Lost Soul Down", music: "musics/20lost_soul.mp3", image: "assets/images/20__.png", artis: "NBSPLV", isLiked: false, isSaved: false),
  Musics(id: 21, name: "Perfect", music: "musics/21perfect.mp3", image: "assets/images/21__.png", artis: "Ed Sheeran", isLiked: false, isSaved: false),
  Musics(id: 22, name: "Don't Be So Shy", music: "musics/22dont_be_shy.mp3", image: "assets/images/22__.jpg", artis: "Imany", isLiked: false, isSaved: false),
  Musics(id: 23, name: "Family Affair", music: "musics/23family_affair.mp3", image: "assets/images/23__.png", artis: "Mary J.Blige", isLiked: false, isSaved: false),
  Musics(id: 24, name: "Set Fire To The Rain", music: "musics/24set_fire.mp3", image: "assets/images/24__.png", artis: "Adele", isLiked: false, isSaved: false),
  Musics(id: 25, name: "Until I Found You", music: "musics/25until_found_you.mp3", image: "assets/images/25__.png", artis: "Stephen Sanchez & Em Beihold", isLiked: false, isSaved: false),
  Musics(id: 26, name: "Bling-Bang-Bang-Born", music: "musics/26bling_bang.mp3", image: "assets/images/26__.png", artis: "Creepy Nuts", isLiked: false, isSaved: false),
  Musics(id: 27, name: "Paint The Town Red", music: "musics/27paint_town_red.mp3", image: "assets/images/27__.png", artis: "Doja Cat", isLiked: false, isSaved: false),
  Musics(id: 28, name: "Way Down We Go", music: "musics/28way_down_go.mp3", image: "assets/images/28__.png", artis: "KALEO", isLiked: false, isSaved: false),
  Musics(id: 29, name: "Sabriy 'Aalil'", music: "musics/29sabry.mp3", image: "assets/images/29__.png", artis: "Sherine", isLiked: false, isSaved: false),
  Musics(id: 30, name: "Commas", music: "musics/30commas.mp3", image: "assets/images/30__.png", artis: "Ayra Starr", isLiked: false, isSaved: false),
  Musics(id: 31, name: "Him and I", music: "musics/31him_and_i.mp3", image: "assets/images/31__.png", artis: "G-Eazy & Halsey", isLiked: false, isSaved: false),
  Musics(id: 32, name: "Sweat Dreams", music: "musics/32sweat_dreams.mp3", image: "assets/images/32__.png", artis: "Eurythmics", isLiked: false, isSaved: false),
  Musics(id: 33, name: "Say Yes...eaven", music: "musics/33say_yes.mp3", image: "assets/images/33__.png", artis: "Lana Del Rey", isLiked: false, isSaved: false),
  Musics(id: 34, name: "Golden Mood", music: "musics/34golden_mood.mp3", image: "assets/images/34__.png", artis: "Iann Dior", isLiked: false, isSaved: false),
  Musics(id: 35, name: "Becane", music: "musics/35becane.mp3", image: "assets/images/35__.png", artis: "Yame", isLiked: false, isSaved: false),
  Musics(id: 36, name: "Aesthetic", music: "musics/36aesthetic.mp3", image: "assets/images/36__.png", artis: "Tollan Kim", isLiked: false, isSaved: false),
  Musics(id: 37, name: "Boss", music: "musics/37boss.mp3", image: "assets/images/37__.png", artis: "Jony, The Limba", isLiked: false, isSaved: false),
  Musics(id: 38, name: "Docha", music: "musics/38docha.mp3", image: "assets/images/38__.png", artis: "Jah Khalib", isLiked: false, isSaved: false),
  Musics(id: 39, name: "Ku Lo Sa", music: "musics/39oxlade.mp3", image: "assets/images/39__.png", artis: "Oxlade", isLiked: false, isSaved: false),
  Musics(id: 40, name: "Funk Of Suffering", music: "musics/40funk_of_suffering.mp3", image: "assets/images/40__.png", artis: "SXID", isLiked: false, isSaved: false),
  Musics(id: 41, name: "Middle Of the night", music: "musics/41middle_of_night.mp3", image: "assets/images/41__.png", artis: "Elley Duhe", isLiked: false, isSaved: false),
  Musics(id: 42, name: "MTG-Brazillian Pista Danca", music: "musics/42brazillian_pista.mp3", image: "assets/images/42__.png", artis: "MTG", isLiked: false, isSaved: false),
  Musics(id: 43, name: "Neon Blade", music: "musics/43neon_blade.mp3", image: "assets/images/43__.png", artis: "Moodn Deity", isLiked: false, isSaved: false),
  Musics(id: 44, name: "Dj FKU...", music: "musics/44dj_fkun.mp3", image: "assets/images/44__.png", artis: "DJ MoiGus", isLiked: false, isSaved: false),
  Musics(id: 45, name: "Fight Back", music: "musics/45fight_back.mp3", image: "assets/images/45__.jpg", artis: "Neffex", isLiked: false, isSaved: false),
  Musics(id: 46, name: "Disaster", music: "musics/46disaster.mp3", image: "assets/images/46__.png", artis: "KsLv Noh", isLiked: false, isSaved: false),
  Musics(id: 47, name: "детство", music: "musics/47detsvo.mp3", image: "assets/images/47__.png", artis: "Rauf And Faik", isLiked: false, isSaved: false),
  Musics(id: 48, name: "It's You", music: "musics/48its_you.mp3", image: "assets/images/48__.png", artis: "Ali Gatie", isLiked: false, isSaved: false),
  Musics(id: 49, name: "Animal", music: "musics/49animal.mp3", image: "assets/images/49__.png", artis: "Rauf And Faik", isLiked: false, isSaved: false),
  Musics(id: 50, name: "Alucard-Rap", music: "musics/50alucard.mp3", image: "assets/images/50__.png", artis: "Rustage", isLiked: false, isSaved: false),
  Musics(id: 51, name: "Into Your Arms", music: "musics/51into_your_arms.mp3", image: "assets/images/51__.png", artis: "Neko GMV - Ava Max", isLiked: false, isSaved: false),
  Musics(id: 52, name: "Воздушный сарафан", music: "musics/52jony.mp3", image: "assets/images/52__.png", artis: "Jony", isLiked: false, isSaved: false),
  Musics(id: 53, name: "Papoutai", music: "musics/53papoutai.mp3", image: "assets/images/53__.png", artis: "StromaeiVevo", isLiked: false, isSaved: false),
  Musics(id: 54, name: "Sequencia Da D27 (Funk Br)", music: "musics/54sequence.mp3", image: "assets/images/54__.png", artis: "TRASHXRL", isLiked: false, isSaved: false),
  Musics(id: 55, name: "Life Goes On", music: "musics/55life_goes_on.mp3", image: "assets/images/55__.jpg", artis: "LatinHype-Oliver Tree", isLiked: false, isSaved: false),
  Musics(id: 56, name: "Gunah Benim", music: "musics/56gunah_benim.mp3", image: "assets/images/56__.png", artis: "Eypio & Burak King", isLiked: false, isSaved: false),
  Musics(id: 57, name: "Step-Back", music: "musics/57step_back.mp3", image: "assets/images/57__.png", artis: "1only", isLiked: false, isSaved: false),
  Musics(id: 58, name: "Alleya", music: "musics/58alleya.mp3", image:"assets/images/58__.png", artis: "Jony", isLiked: false, isSaved: false),
  Musics(id: 59, name: "Isa", music: "musics/59isa.mp3", image: "assets/images/59__.png", artis: "Andro", isLiked: false, isSaved: false),
  Musics(id: 60, name: "Wetsie Boogie", music: "musics/60wetsie_boogie.mp3", image: "assets/images/60__.png", artis: "Jeshi - Protein", isLiked: false, isSaved: false),
  Musics(id: 61, name: "Love Story", music: "musics/61love_story.mp3", image: "assets/images/61__.png", artis: "Indila", isLiked: false, isSaved: false),
  Musics(id: 62, name: "Миллионы Причин", music: "musics/62million_prichin.mp3", image: "assets/images/62__.png", artis: "Konfuz", isLiked: false, isSaved: false),

];
